export const textures = {
  rocky: ['rocky1.jpg', 'rocky2.jpg', 'rocky3.jpg'],
  icy: ['icy1.jpg', 'icy2.jpg', 'icy3.jpg'],
  sun: ['sun1.jpg', 'sun2.jpg'],
  gas: ['gas1.jpg', 'gas2.jpg', 'gas3.jpg'],
  earthLike: ['earth.jpg'],
};

// const data =        {
// planetName: system.pl_name,
// starName: system.hostname,
// numberOfStars: system.sy_snum,
// numberOfPlanets: system.sy_pnum,
// discoveryMethod: system.discoverymethod,
// yearDiscovered: system.disc_year,
// discoveryFacility: system.disc_facility,
// isControversial: system.pl_controv_fla,
// planetOrbitTimeD: system.pl_orbper,
// orbitDistanceAU: system.pl_orbsmax,
// planetRadiusE: system.pl_rade,
// planetMassE: system.pl_bmasse,
// planetDensity: system.pl_dens,
// planetOrbitEccentricity: system.pl_orbeccen,
// planetTemp: system.pl_eqt,
// planetOrbitToStarRatio: system.pl_ratror,
// starSpectralType: system.st_spectype,
// starTempK: system.st_teff,
// starRadiusS: system.st_rad,
// starMassS: system.st_mass,
// starLuminosity: system.st_lum,
// starAge: system.st_age,
// starDensity: system.st_dens,
// starRotationVelocity: system.st_vsin,
// starRotationTimeD: system.st_rotp,
// gLat: system.glat,
// gLon: system.glon,
// eclipticLat: system.elat,
// eclipticLon: system.elon,
// distancePC: system.sy_dist,}
